pennlabs/penn-mobile

Pipfile, Pipfile.lock, gsr_booking/serializers.py, gsr_booking/tests.py, gsr_booking/views.py
This PR makes it so users can only see details of other users that they should be allowed to see.
Previously, you could look up all groups any user was a part of just by hitting the `/users` endpoint. Now, when you hit that endpoint, you will only see groups for users which you are also a member of.
=> Protect /user/ endpoints

backend/gsr_booking/models.py, backend/pennmobile/settings/base.py, backend/pennmobile/settings/ci.py, backend/pennmobile/test_runner.py, backend/tests/dining/test_views.py, backend/tests/gsr_booking/test_gsr_booking.py, backend/tests/gsr_booking/test_gsr_views.py, backend/tests/gsr_booking/test_gsr_wrapper.py, backend/tests/laundry/test_views.py, backend/tests/penndata/test_views.py, backend/tests/portal/test_permissions.py, backend/tests/portal/test_polls.py, backend/tests/portal/test_posts.py, backend/tests/user/test_notifs.py, backend/tests/user/test_user.py
Override XML Test Runner to allow for test suite-wide Mock Patches
- Currently used to Patch API requests to Wharton GSR API
=> Override Django XML Test Runner

k8s/main.ts
`get_fitness_snapshot` as opposed to `get_fitness_snapshots`
=> Fix Cronjob Typo For Fitness Snapshots

backend/gsr_booking/api_wrapper.py
- Does not work with incoming transfer students. 
- Next steps are to implement this again with a cron job to reset the `is_wharton` field for users regularly.
=> [Bug] Remove is_wharton Cache

backend/dining/api_wrapper.py, backend/tests/dining/test_views.py
Instead of requesting data from UPenn every time the `/api/dining/venues` endpoint is, we gather the data from the DiningMenu objects we already hold.
=> Refactor Get Venues

backend/laundry/api_wrapper.py, backend/pennmobile/settings/base.py, backend/tests/laundry/test_api_wrapper.py, backend/tests/laundry/test_commands.py
- Problem: unable to hit Penn's Laundry endpoint outside of Penn's network
- [TEMPORARY SOLUTION]: hit a different URL that acts as Laundry endpoint (info provided by Raspberry pi on Penn's network that basically makes laundry info info accessible to outside Penn's network)
=> Laundry Temp Fix

backend/penndata/urls.py, backend/penndata/views.py, backend/tests/penndata/test_views.py
* Adds `eventcount/` endpoint under portal app to return the number of unique interactions for either polls or posts
* Adds test cases for new endpoint
=> Unique Portal Visits

backend/laundry/api_wrapper.py
* Due to hacky laundry fix, status endpoint doesn't work. Defaulting the answer to status "working" for now.
=> Override Laundry Status Endpoint

backend/gsr_booking/management/commands/labs_gsr_data.py
Modifies the `labs_gsr_data` command to not show canceled GSR bookings.
=> Ignore Canceled GSR Bookings

.github/workflows/cdkactions_build-and-deploy.yaml, .github/workflows/cdkactions_validate.yaml, backend/Pipfile, backend/Pipfile.lock, backend/penndata/models.py
Removes deprecated `codecov` package from backend environment. Disables the CI/CD steps that involve the package.
=> Remove Deprecated Codecov

backend/penndata/views.py
Fixing: https://penn-labs.slack.com/archives/C05Q2MEGY3T/p1694365151920569
=> Fix Fitness Aggregation

k8s/main.ts
- Populates new target populations every August (particularly important for adding new graduation year)
=> Target Populations Cronjob Every August

backend/laundry/views.py
=> Fix Laundry Snapshot Collection

backend/laundry/views.py
Previous attempt at a solution failed. This is a dumber but more guaranteed way to avoid the error. Will investigate and revert later once root issue is identified.
=> Temporary Laundry Patch 

backend/dining/urls.py, backend/dining/views.py, backend/laundry/views.py, backend/tests/sublet/test_sublets.py
=> Cache Dining

backend/gsr_booking/management/commands/individual_usage.py, backend/user/management/commands/profile_info.py
=> Info Commands

backend/dining/api_wrapper.py, backend/gsr_booking/api_wrapper.py, backend/utils/errors.py
added superclassconfig.py, edited api_wrapper.py and apps.py in dining
=> Better way to pass API Error for all files in backend folder

.git-blame-ignore-revs
Everyone needs to run to update their git config file to use the added file:`git config blame.ignoreRevsFile .git-blame-ignore-revs`
Also github should automatically pick up on it
=> Add git blame ignore for black upgrade

backend/pennmobile/admin.py
makes sure django-labs-account uses our custom admin (and not overrides it)
=> Fix Custom Admin

backend/gsr_booking/admin.py
For easy adding/removing users to groups
=> Make GSR Group Admin easy to add/remove users

backend/gsr_booking/serializers.py, backend/gsr_booking/urls.py, backend/gsr_booking/views.py, backend/tests/gsr_booking/test_gsr_booking.py, backend/tests/user/test_notifs.py, backend/user/models.py
We did a GSR refactor that removed the need for "Me" groups last year
- "Me" groups existed in the first place so we could treat booking GSRs for users the same as booking GSRs for groups.
- Turns out the logic can be optimized if we separate the use cases so we did just that in the GSR refactor, using `group=None` to just book the group for the given user. 
This PR removes the the leftovers to __erase the idea of "Me" groups completely from our codebase__. 
Also did a small refactor with a group membership view. 
- __Note__: I checked iOS code and `users` (now `/mymemberships`), `membership`, and `groups` isn't used at all
- We probably will never implement group feature. But its probably worth refactoring this code so that it makes sense, _eventually_. Since if we are going to keep it, …
=> Remove Me Groups

backend/user/views.py
This feels a little bad. The assumption we are making is that people will not get ahold of someone else's device's notification token. 
But the worst that could happen is the attacker can hijack notifications sent to the device. The attacker will never get ahold of notifications actually meant for the user since users must be logged in to become associated with a particular token. 
TODO: add test in later PR
=> Allow Anyone Delete Token

k8s/main.ts
Path to credentials sent on slack. They are in `/app` but so is the `ios-key`, so we can just migrate them altogether eventually.
=> [Notifications] Add APNS and FCM Credentials

backend/user/notifications.py, backend/user/views.py
ex: 
`{'aps': {'alert': {'title': 'a', 'body': 'b'}, 'badge': 0, 'sound': 'default', 'mutable-content': 1, 'interruption-level': 'time-sensitive'}}`
=> Add Urgent Notif (iOS)

.github/workflows/build-and-deploy.yaml, .github/workflows/validate.yaml
The Kubernetes deployment script must be updated to v0.1.5 to properly deploy (see pennlabs/penn-clubs).
=> Bump shared actions version

backend/wrapped/serializers.py
Include the `id` field in the JSON response for wrapped pages.
=> make ID serialize with page model
