pennlabs/penn-mobile

booking/serializers.py
booking/views.py

On the ios side, we want to show the color on the first fetch of user's groups. Adding this one line would do that :D.

Show color for group in user view

---

README.md
booking/models.py
booking/views.py

Database now allows user to define if it allows it's pennkey to be used and if it wants to receive notifications for particular groups.

Pennkey Allowance + Notification

---

gsr_booking/csrfExemptSessionAuthentication.py
gsr_booking/views.py

Simply overrode the enforce_csrf method.

Fixed CSRF by extending SessionAuthentication

---

gsr_booking/booking_logic.py
gsr_booking/serializers.py
gsr_booking/tests.py
gsr_booking/views.py

Sample request JSON looks like this:
`{
"room_bookings":[
{
"room": 7282,
"start":"2020-03-25T21:30:00.000Z",
"end":"2020-03-25T22:30:00.000Z",
"lid": 1090
},
{
"room": 7282,
"start":"2020-03-25T22:30:00.000Z",
"end":"2020-03-25T23:30:00.000Z",
"lid": 1090
}
]
}`

Added support for simultaneously booking multiple rooms

---

backend/portal/views.py
backend/tests/portal/test_polls.py

Portal backend polls: polls status view

---

backend/penndata/views.py
backend/tests/penndata/test_views.py

Changed calendar response to be an array rather than a nested array with a calendar field

removed calendar field from json response

---

backend/gsr_booking/booking_logic.py
backend/gsr_booking/serializers.py
backend/gsr_booking/urls.py
backend/gsr_booking/views.py
backend/pennmobile/urls.py
backend/tests/gsr_booking/test_gsr_booking.py

Reverts pennlabs/penn-mobile#92

Revert "GSR Booking Test Fix"

---

backend/tests/user/test_notifs.py
backend/user/models.py

- Commenting out Post-Save to stop NotificationSetting creation
- Editing Test Cases accordingly (TODO: revert test case changes)

Rolling Back Post-Save hook for Notif Setting creation

---

k8s/main.ts

Follow-up from last [PR](https://github.com/pennlabs/penn-mobile/pull/108) for consistency purposes.

[Deployment] Fix cronjob typo

---

backend/dining/api_wrapper.py
backend/dining/views.py
backend/pennmobile/settings/base.py
backend/tests/dining/test_views.py

Part 1 of a fix to migrate dining API to new Penn OpenShift platform.
Current Changes:
- Venue Name
- Venue Hours

[Dining API Fix #1] Migrated Venue Name and Venue Hours

---

backend/pennmobile/settings/base.py
backend/pennmobile/settings/ci.py
backend/pennmobile/settings/development.py
backend/pennmobile/test_runner.py

https://app.shortcut.com/pennlabs/story/3730/utilities-v1-remove-xml-runner-for-local-testing

Utilities V1 - Remove XML Runner for local testing

---

frontend/package.json
frontend/yarn.lock

Reverts pennlabs/penn-mobile#112

Revert "Bump moment from 2.29.1 to 2.29.4 in /frontend"

---

frontend/package.json
frontend/yarn.lock

Reverts pennlabs/penn-mobile#123
Originally pennlabs/penn-mobile#112

Revert "Revert "Bump moment from 2.29.1 to 2.29.4 in /frontend""

---

backend/dining/api_wrapper.py

Optimize Dining Load

---

backend/gsr_booking/api_wrapper.py
backend/gsr_booking/group_logic.py
backend/tests/gsr_booking/test_gsr_wrapper.py

https://app.shortcut.com/pennlabs/story/3754/gsr-update-v2-book-in-30-minute-intervals

Group GSR Fix 

---

backend/user/notifications.py

Notification iOS Message

---

k8s/package.json
k8s/yarn.lock

updated kittyhawk to 1.17 for kubernetes upgrade to 1.22

bumped version of kittyhawk to 1.17

---

backend/laundry/api_wrapper.py

- Updates `status` post request to have appropriate headers

Laundry Temp Fix v2

---

backend/laundry/api_wrapper.py

Reverts pennlabs/penn-mobile#166

Revert "Override Laundry Status Endpoint"

---

backend/gsr_booking/api_wrapper.py
backend/gsr_booking/group_logic.py

- Changed the error for querying our models to 404.
- Fixed failing test case (changed lid to gid for get_availability)

GSR Change Model Query Errors to 404

---

backend/tests/user/test_notifs.py
backend/user/views.py

- Changed `NotificationAlertView` to handle B2B
- Changed `NotificationSettingsView` to handle B2B

B2B Notifications

---

backend/portal/logic.py
backend/tests/portal/test_polls.py
backend/tests/user/test_notifs.py

Categorized the TargetPopulations by Major, Degree, Etc. for easier time to parse.

Vote Statistics Cleaner JSON

---

backend/gsr_booking/management/commands/change_group.py
backend/gsr_booking/management/commands/get_reservations.py
backend/gsr_booking/management/commands/labs_gsr_data.py
backend/gsr_booking/management/commands/load_gsrs.py
backend/laundry/api_wrapper.py

Shortcuts:
https://app.shortcut.com/pennlabs/story/3791/gsr-update-v1-fix-internal-group-gsr-tool
https://app.shortcut.com/pennlabs/story/3919/scripts-to-write-for-business-development

GSR Commands

---

backend/penndata/urls.py
backend/penndata/views.py
backend/tests/penndata/test_views.py
backend/user/models.py
backend/user/serializers.py

Please review this, I have no idea what I'm doing so I probably missed something. This should just add user preferences for which fitness locations they favorited, and it should be similar/identical to the way laundry works.
I also tried to test it out, and while it runs, I couldn't figure out how (or became too lazy) to make a test user that can get authentication to test the route.

User Fitness Preferences

---

backend/penndata/views.py

Modified fitness rooms route to return a list of open times for the week rather than the current open time for each room. Same for close.

Fitness Rooms Return List for Open/Close

---

backend/Pipfile.lock

Update DLA to 0.9.3 to reflect some bug fixed with login

Update DLA and corresponding dependencies

---

backend/tests/penndata/test_views.py

Fix Fitness Usage Tests

---

backend/tests/utils/test_r_request.py
backend/utils/r_request.py

Creating `RRequest` class to robustly return a probabilistically valid response to our Django apps in the presence of one-off malformed data or invalid responses from external APIs

Robust Request Class for Penn APIs

---

k8s/main.ts

Disallows HTTP request and redirect to HTTPS.

Enforce HTTPS for Mobile

---

backend/laundry/views.py
backend/tests/user/test_notifs.py

Will uncomment these tests once Platform fixed.

Fix Notification Tests

---

backend/laundry/views.py

Swift parsers are weird and broke from the previous solution. We go again.

Temporary Laundry Patch #2

---

backend/.devcontainer/Dockerfile
backend/.devcontainer/devcontainer.json

https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/common.md
Note: if there are command prompt slowdowns there is some fix in the bottom of the article.
Future TODOs:
- `oh-my-zsh` plugins such as auto-complete
- Python syntax highlighting extensions
- Speed up command prompt (can probably use a `postCreateCommand` in the `devcontainer.json`

Basic Dev Container for Backend

---

backend/pennmobile/admin.py
backend/pennmobile/settings/base.py
backend/pennmobile/urls.py
backend/portal/admin.py
backend/portal/models.py
backend/user/views.py

- Add info to changelist views + sort by "action required" on top
- Put poll votes inline
- Add quick drop down actions for post/polls
- make default admin page custom in order to add notif messages to homepage
- Add messages on home page to instantly see how many post/polls need review

Portal Admin Prettify

---

.github/workflows/build-and-deploy.yaml
frontend/next.config.js
frontend/package.json
frontend/postcss.config.js
frontend/stylesheets/globals.css
frontend/tailwind.config.js
frontend/yarn.lock

- Add TailwindCSS to frontend because existing CSS is a big pain to wrangle.
- Will eventually do refactors to uniform Tailwind.

add tailwind css to frontend

---

backend/pennmobile/urls.py

Reverts pennlabs/penn-mobile#344

Revert "universal identifier link for ios"

---

backend/pennmobile/urls.py

Reverts pennlabs/penn-mobile#345
(Revert "Revert "universal identifier link for ios"")

Try Universal Identifier Link for ios again
